# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/rumsdb
spring.datasource.username=postgres
spring.datasource.password=078868
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

# JWT
rums.jwt.secret=fRJFjsT7KXtMxw/GrpQzG3PUyAxljq2tlQda7zR7vFM=
rums.jwt.access-expiry-seconds=28800
rums.jwt.refresh-expiry-seconds=604800

# File storage
rums.files.upload-dir=./uploads/

# Mail (for user invites)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hirwajuspin4@gmail.com
spring.mail.password=rglndxrlokywfkdp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# CORS
rums.cors.allowed-origin=http://localhost:3000

# Server
server.port=8080
spring.application.name=rums-api

# JPA
spring.jpa.open-in-view=false

# Backup
rums.backup.dir=./backups/
